allowBuilds:
  better-sqlite3: false
  esbuild: true
  protobufjs: true
  sqlite3: true
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - sqlite3
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@atomone/*'
  - '@gnolang/*'
