validation: sovereign
version: 1
accounts:
    - name: alice
      coins:
        - 2000000000udenom
      mnemonic: other razor era scene permit morning lend scrub habit beyond mixed icon alcohol fuel news glory alien actual bachelor spell album fitness squeeze energy
    - name: bob
      coins:
        - 100000000udenom
faucet:
    name: bob
    coins:
        - 100000udenom
    port: 4501
default_denom: udenom
validators:
    - name: alice
      bonded: 100000000udenom
      app:
        api:
            address: tcp://localhost:1318
            enable: true
            max-open-connections: "1000"
            swagger: true
        grpc:
            address: localhost:9091
            enable: true
      config:
        p2p:
            laddr: tcp://0.0.0.0:26659
        rpc:
            laddr: tcp://0.0.0.0:26658
