export const Timeout = `package main

import (
  "encoding/hex"

  "gno.land/p/aib/ibc/types"
  "gno.land/p/aib/ics23"
  "gno.land/r/aib/ibc/core"
)

func hexDec(s string) []byte {
  if s == "" {
    return nil
  }
  b, err := hex.DecodeString(s)
                 if err != nil { panic(err) }
  return b
}

func main() {
  // Timeout the packet
  specs := ics23.IavlSpec()
  timeoutPacket := types.MsgTimeout{
    Packet: types.Packet{
      Sequence:          {{ sequence }},                        // XXX update
      SourceClient:      "{{ sourceClient }}",                // XXX update
      DestinationClient: "{{ destinationClient }}",          // XXX update
      TimeoutTimestamp:  uint64({{timestamp}}), // XXX update: must be the same as the timestamp of the send packet
      Payloads: []types.Payload{
      {{#each payloads}}
      {
        SourcePort:      "{{ this.sourcePort }}",             // XXX update
        DestinationPort: "{{ this.destinationPort }}", //XXX update
        Encoding:        "{{ this.encoding }}",
        Value:           hexDec("{{ this.value }}"),           // XXX update: the packet data
        Version:         "{{ this.version }}",         // XXX update: version of app (transfer uses v1)
      },
      {{/each}}
      },
    },
    // Write the proof that no RecvPacket have been received by the counterparty
    // chain.
    // NOTE proof generated by go run -C ./cmd/gen-proof . -exist=false MERKLE_PREFIX CLIENT_ID commitment
    ProofUnreceived: {{{ commitmentProof }}},
    ProofHeight: types.NewHeight({{ proofRevision }}, {{ proofHeight }}), // XXX update
  }

  res := core.Timeout(cross, timeoutPacket)

  println(res)
}

// Error:
// invalid Payload #0: payload value cannot be empty`;
